-- ============================================================
-- ETL pg_cron schedule for etl-gme-psv
-- ============================================================
--
-- This migration is INTENTIONALLY DOCUMENTATION-ONLY (no DDL).
--
-- The actual cron.schedule call embeds the SUPABASE_SERVICE_ROLE_KEY which
-- must NOT be committed to version control. The schedule was applied
-- one-time via Supabase MCP / SQL Editor by an administrator with
-- service_role privileges.
--
-- ## Active schedule (informational)
--
-- jobname:  etl-gme-psv-daily
-- schedule: '0 17 * * *' (UTC) = 19:00 CEST (summer) / 18:00 CET (winter)
--           Always >1h after MGP-GAS auction close at ~17:00 Europe/Rome.
-- target:   https://epbluenhmdwgmgcewrsf.supabase.co/functions/v1/etl-gme-psv
-- auth:     Bearer <SUPABASE_SERVICE_ROLE_KEY> (in .env.local, gitignored)
--
-- Why UTC: cron.timezone cannot be changed on Supabase managed Postgres.
-- The 1h DST drift twice a year is acceptable: ETL stays >1h after auction
-- close in both regimes.
--
-- ## How to re-apply (if cron entry is lost or need to restore)
--
-- Run from Supabase Dashboard SQL Editor (logged in as project owner):
--
--   SELECT cron.schedule(
--     'etl-gme-psv-daily',
--     '0 17 * * *',
--     $$
--     SELECT net.http_post(
--       url := 'https://epbluenhmdwgmgcewrsf.supabase.co/functions/v1/etl-gme-psv',
--       headers := jsonb_build_object(
--         'Content-Type', 'application/json',
--         'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY_HERE'
--       ),
--       timeout_milliseconds := 60000
--     ) as request_id;
--     $$
--   );
--
-- ## How to verify
--
--   SELECT jobid, schedule, jobname, active FROM cron.job
--   WHERE jobname = 'etl-gme-psv-daily';
--
--   SELECT id, source, status, started_at, rows_ingested
--   FROM etl_runs WHERE source='gme-psv'
--   ORDER BY id DESC LIMIT 5;
--
-- ## How to unschedule
--
--   SELECT cron.unschedule('etl-gme-psv-daily');

-- No-op statement so the migration applies cleanly:
SELECT 1 AS pg_cron_etl_psv_documented;
