-- ============================================================
-- ETL ARERA — NON usa pg_cron (ARERA blocca IP egress Supabase con 403)
-- ============================================================
-- Doc-only migration (no DDL).
--
-- !!! DEPRECATED — NON attivare questo schedule !!!
--
-- Test 2026-05-12: l'edge function `etl-arera-placet` riceve 403 Forbidden
-- (Microsoft IIS WAF) quando chiama ARERA dal range IP Supabase/AWS.
-- Le stesse URL funzionano da locale e da GitHub Actions runner.
--
-- Workaround attivo: l'ETL gira da GitHub Actions schedulato.
-- File: .github/workflows/etl-arera-daily.yml
-- Schedule: '0 1 * * *' UTC (= 03:00 CEST / 02:00 CET)
-- Riusa lo script `scripts/backfill-arera-placet.ts` con
-- BACKFILL_START=BACKFILL_END=today.
-- Secrets richiesti nel repo GitHub: SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY.
--
-- L'edge function `etl-arera-placet` resta deployata ma NON deve essere
-- chiamata da pg_cron — fallirebbe ogni giorno con 403 e riempirebbe
-- etl_runs di errori inutili.
--
-- Pattern storico (lasciato qui per riferimento se ARERA toglie il block):
--
-- How to re-apply (Supabase Dashboard SQL Editor):
--
--   SELECT cron.schedule(
--     'etl-arera-placet-daily',
--     '0 0 * * *',
--     $$
--     SELECT net.http_post(
--       url := 'https://epbluenhmdwgmgcewrsf.supabase.co/functions/v1/etl-arera-placet',
--       headers := jsonb_build_object(
--         'Content-Type', 'application/json',
--         'Authorization', 'Bearer YOUR_SERVICE_ROLE_KEY_HERE'
--       ),
--       timeout_milliseconds := 120000
--     ) as request_id;
--     $$
--   );
--
-- How to verify:
--
--   SELECT jobid, schedule, jobname, active FROM cron.job
--   WHERE jobname = 'etl-arera-placet-daily';
--
--   SELECT id, source, status, started_at, rows_ingested
--   FROM etl_runs WHERE source='arera-placet'
--   ORDER BY id DESC LIMIT 5;

SELECT 1 AS pg_cron_etl_arera_documented;
